// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth.proto
	verification.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
	VerificationRequest
	VerificationResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthResponse_AuthResultCode int32

const (
	AuthResponse_SUCCESS AuthResponse_AuthResultCode = 0
	AuthResponse_FAIL    AuthResponse_AuthResultCode = 1
)

var AuthResponse_AuthResultCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}
var AuthResponse_AuthResultCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x AuthResponse_AuthResultCode) String() string {
	return proto1.EnumName(AuthResponse_AuthResultCode_name, int32(x))
}
func (AuthResponse_AuthResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type AuthRequest struct {
	ClientId     string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto1.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AuthRequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type AuthResponse struct {
	Result AuthResponse_AuthResultCode `protobuf:"varint,1,opt,name=result,enum=proto.AuthResponse_AuthResultCode" json:"result,omitempty"`
	Token  string                      `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto1.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResponse) GetResult() AuthResponse_AuthResultCode {
	if m != nil {
		return m.Result
	}
	return AuthResponse_SUCCESS
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto1.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto1.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto1.RegisterEnum("proto.AuthResponse_AuthResultCode", AuthResponse_AuthResultCode_name, AuthResponse_AuthResultCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	DoAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) DoAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/proto.Auth/DoAuth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	DoAuth(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_DoAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).DoAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/DoAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).DoAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoAuth",
			Handler:    _Auth_DoAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto1.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xfe, 0x5c, 0xdc, 0x8e, 0xa5,
	0x25, 0x19, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xd2, 0x5c, 0x9c, 0xc9, 0x39, 0x99,
	0xa9, 0x79, 0x25, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x1c, 0x10, 0x01,
	0xcf, 0x14, 0x21, 0x65, 0x2e, 0x5e, 0xa8, 0x64, 0x71, 0x6a, 0x72, 0x51, 0x6a, 0x89, 0x04, 0x13,
	0x58, 0x01, 0x0f, 0x44, 0x30, 0x18, 0x2c, 0xa6, 0xd4, 0xc9, 0xc8, 0xc5, 0x03, 0x31, 0xb1, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x8a, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0x6c,
	0x1e, 0x9f, 0x91, 0x12, 0xc4, 0x01, 0x7a, 0xc8, 0x8a, 0x60, 0x9c, 0xd2, 0x9c, 0x12, 0xe7, 0xfc,
	0x94, 0xd4, 0x20, 0xa8, 0x0e, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0xa8, 0x4d,
	0x10, 0x8e, 0x92, 0x3a, 0x17, 0x1f, 0xaa, 0x7a, 0x21, 0x6e, 0x2e, 0xf6, 0xe0, 0x50, 0x67, 0x67,
	0xd7, 0xe0, 0x60, 0x01, 0x06, 0x21, 0x0e, 0x2e, 0x16, 0x37, 0x47, 0x4f, 0x1f, 0x01, 0x46, 0x23,
	0x6b, 0x2e, 0x16, 0x90, 0x42, 0x21, 0x63, 0x2e, 0x36, 0x97, 0x7c, 0x30, 0x4b, 0x08, 0xc5, 0x72,
	0xb0, 0x9f, 0xa5, 0x84, 0xb1, 0x38, 0x48, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x6a, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x01, 0x5f, 0x5b, 0x32, 0x35, 0x01, 0x00, 0x00,
}
